### ISSUE TITLE
Secrets

### ISSUE THREAD

**Issue by devkeydet** [cschleiden/replace-tokens#18]
Is there a syntax to replace a token from a secret instead of environment variable?

**Comment by cschleiden** [comment]
The action doesn't have access to your secrets, you'd have to set an environment variable to the value of your secret. Something like:

```yaml
env:
  MY_SECRET: ${{ secrets.MY_SECRET }}
```

**Comment by devkeydet** [comment]
I found this action that comes in handy:
https://github.com/marketplace/actions/secrets-to-environment-variables

**Comment by jornbeyers** [comment]
How would I need to do this in case my input is a secret and contains a json with multiple secrets? In the past I just used a variable in combination with the `fromJson()` command but now I am dealing with secrets and the fromJson does not accept secrets it seems.

```yml
    secrets:
      BICEP_PARAMETERS_TOKENS:
        required: false

...

      - name: Tokenize Bicep Parameters
        uses: cschleiden/replace-tokens@v1
        env: ${{ fromJson(secrets.BICEP_PARAMETERS_TOKENS) }}
        with:
          files: ${{ inputs.BICEP_PARAMETERS_FILE }}

```
