### ISSUE TITLE
Removing content when not replace

### ISSUE THREAD

**Issue by ghost** [cschleiden/replace-tokens#24]
Hello, 

When I use this action on a file that has the same pattern in a parameter that I don't want to replace - and therefore not sending it, the task will replace it with empty string.

for example:

File a.txt:
```
a=#{param}#
b=#{nana}#
``` 

task:
```
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          files: '["a.txt"]'
        env:
          param: lala
```

at the end the file will be:
```
a=lala
b=
```

but I would like it to be:
```
a=lala
b=#{nana}#
```
I think it should replace the parameter only if I gave it.
