### ISSUE TITLE
GitHub Actions is not replacing the token in file

### ISSUE THREAD

**Issue by anaskhandevops** [cschleiden/replace-tokens#32]
Hey, I'm newbie at GitHub Actions. When I push the changes, GitHub actions is started where I am using the *cschleiden/replace-tokens* to replace the image tag in deployment.yaml. The build was success but not updating the changes in K8s manifest file.

![image](https://user-images.githubusercontent.com/105498424/220861268-6491debc-35f2-4886-8c1e-59cbc09a259d.png)

My repo is connected with ArgoCD. when i push the changes, it automatically detect the changes and deploy the app and what i am getting error on ArgoCD Ui:
![image](https://user-images.githubusercontent.com/105498424/220877429-0708ff24-5d77-4530-8d6e-10c58477b83f.png)

In Detail:
![image](https://user-images.githubusercontent.com/105498424/220877576-019698ec-4a88-49b2-9584-6d4756f299c4.png)

**Repository**: 
```
https://github.com/1DevOps2/docker-gs-ping
```

**ci.yml**
```
name: Go Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }} # name of Docker Hub ID
      IMAGE_NAME: docker-gs-ping
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER

    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG

    - name: Docker Push
      run: docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
      
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.2
      with:
        files: '["*.yaml"]'
        tokenPrefix: '__' # optional, default is #{
        tokenSuffix: '__' # optional, default is }#
      env:
        DOCKER_REPOSITORY: ${{ env.DOCKER_REPOSITORY }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

```

**deployment.yaml**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  selector:
    matchLabels:
      app: go
  replicas: 1
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go-app
        image: __DOCKER_REPOSITORY__/__IMAGE_NAME__:__IMAGE_TAG__
        ports:
        - containerPort: 8082
   ```
