### ISSUE TITLE
Odd behavior on a windows agent

### ISSUE THREAD

**Issue by mmisztal1980** [cschleiden/replace-tokens#8]
My workflow contains a stage that uses `replace-tokens` to pre-render a nuget.config file.

```yaml
- uses: cschleiden/replace-tokens@v1
      name: replace-tokens nuget.config
      with:
        files: '["${{ github.workspace }}/.github/tools/nuget.config"]'
      env:
        NUGET_FEED: "${{ secrets.NUGET_FEED }}"
        NUGET_USERNAME: "${{ secrets.NUGET_USERNAME }}"
        NUGET_PASSWORD: "${{ secrets.NUGET_PASSWORD }}"
```

Interestingly, it works fine on ubuntu and macos, however it does not seem to behave the same way on windows
https://github.com/cloud-tek/ion/runs/2470314125?check_suite_focus=true giving me the following error message:

```
 Unexpected token a in JSON at position 5
```

The workflow is a matrix build across 3 different OSes so the build is the same.

Any thoughts?
